GET https://localhost:4300/api/contatos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZTM2MDhmNy1kMTI3LTQyZjEtOTRmZS0wOGRjZWUwNDFkYjMiLCJlbWFpbCI6InRlc3RlQGdtYWlsLmNvbSIsInVuaXF1ZV9uYW1lIjoidGVzdGUiLCJnaXZlbl9uYW1lIjoiSnVuaW5obyBUZXN0ZXMiLCJuYmYiOjE3Mjk3MDQ2NDYsImV4cCI6MTczMDEzNjY0NiwiaWF0IjoxNzI5NzA0NjQ2LCJpc3MiOiJlQWdlbmRhIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdCJ9.v44gt0vqGC2vTIVi9BF1uIRCKRX6WnTDb2N78rqAwKY
